#!/bin/sh
browserify --standalone rmlmarked RMLMarked.js > bundle.js
uglifyjs -o rmlmarked.min.js bundle.js	
browserify rmlmarked.autoload.js > bundle.autoload.js
uglifyjs -o rmlmarked.autoload.min.js bundle.autoload.js